### ISSUE TITLE
Создать карточку поста (для списка)

### ISSUE THREAD

**Issue by vetptzru** [VyacheslavKuznetso/blog#2]
Пример карточки поста: <img width="424" alt="Снимок экрана 2024-06-27 в 14 42 08" src="https://github.com/VyacheslavKuznetso/blog/assets/34694734/5aa25373-7a83-4f05-a0fe-4f558fee617d">

Референс: https://mantine.dev/core/card/

**Comment by VyacheslavKuznetso** [comment]
Создал карточка-блог
